### ISSUE TITLE
Cannot send messages

### ISSUE THREAD

**Issue by khanhct** [barnybug/gogsmmodem#2]
Hi author,
I found a bug related sleep time when sending message. The SendMessage function only works when I insert 'time.Sleep(10 * time.Millisecond)' in sendBody function
`func (self *Modem) sendBody(cmd string, body string, args ...interface{}) (Packet, error) {
	self.tx <- formatCommand(cmd, args...)
	time.Sleep(10 * time.Millisecond)
	self.tx <- body + "\x1a"
	response := <-self.rx
	if _, e := response.(ERROR); e {
		return response, errors.New("Response was ERROR")
	}
	return response, nil
}` it needs a delay time to get response.
Thank you so much!

**Comment by barnybug** [comment]
Hi - thanks for the issue report. That's a weird one, I wonder if it could be detected/configured rather than changing the code for everything?

**Comment by khanhct** [comment]
So I think you should delay a little bit of time there.
